language: java
sudo: true
jdk:
  - oraclejdk8

git:
  depth: 100

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - jdk_switcher use oraclejdk8
  - chmod +x ./travis/*
  - ./travis/install_mysql_5.7.sh
  - mysql -e 'CREATE DATABASE ecommerce_read_model;'
  - mysql -e 'CREATE DATABASE ecommerce_write_model;'
  - sudo service mysql restart

script:
  - ./gradlew check

services:
  - mysql